language: go

go:
  - 1.8
  - master

addon:
  apt:
    packages:
      - python3-setuptools

before_install:
  - sudo pip3 install setuptools
  - cd runtime.py && sudo python3 setup.py install && cd ..
