language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
# services needed
services: mongodb
# command to run tests
script:
  - pytest -s test
