language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python ui/ui_db_crud.py
  - python ui/ui_time_actions.py