language: go

go:
  - 1.8
  - master

python:
  - 3.6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-setuptools
  - cd runtime.py && sudo python3 setup.py install && cd ..
